### ISSUE TITLE
Navigation bar options

### ISSUE THREAD

**Issue by Nicolfo** [SoftEng2-Group-16/thesis-management-project#36]
As a Teacher I want to see on the navigation bar in which page I am in a more clear way (maybe with a background change too)

**Comment by lfmvit** [comment]
Hello, thank you for your feedback, we reworked the layout of our application, now the active state of the navbar it's displayed by setting opposite colors according to the new palette and [complementary colors](https://www.canva.com/colors/color-wheel/)
